openapi: "3.0.0"
info:
  title: Learn Tool REST APIs
  description: Documentation for the Learn Tool REST APIs.
  version: 1.0.0
paths:
  /workspaces:
    post:
      summary: Create a new Workspace
      operationId: create-workspace
      tags:
        - workspace
      requestBody:
        description: Workspace payload.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            example:
              name: "workspaceTest"
      responses:
        '201':
          description: Workspace successfully created.
          headers:
            location:
              description: The location of the created Workspace.
              schema:
                type: string
              example:
                location: /workspaces/workspaceTest
        '409':
          description: A Workspace already exists with this name.
        '422':
          description: >-
            Workspace name empty or incorrect. Allowed characters: [a-zA-Z0-9-_].
  /workspaces/{workspaceName}/cards:
    post:
      summary: Create a new Card
      operationId: create-card
      tags:
        - card
      parameters:
        - name: workspaceName
          in: path
          description: The name of the Workspace.
          required: true
          schema:
            type: string
          example: "workspaceTest"
      requestBody:
        description: Card content payload.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
                - response
              properties:
                question:
                  type: string
                response:
                  type: string
            example:
              question: "This is a question"
              response: "This is a response"
      responses:
        '201':
          description: Card successfully created.
          headers:
            location:
              description: The location of the created Card.
              schema:
                type: string
              example:
                location: /workspaces/workspaceTest/cards/3cf14a93-f8c7-4b6b-ac24-a662ca500c21
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  workspaceName:
                    type: string
                  question:
                    type: string
                  response:
                    type: string
              example:
                id: "3cf14a93-f8c7-4b6b-ac24-a662ca500c21"
                workspaceName: "workspaceTest"
                question: "This is a question"
                response: "This is a response"
        '404':
          description: Workspace not found.
        '409':
          description: A Card already exists with this id.
        '422':
          description: Card content fields null or empty.
  /workspaces/{workspaceName}/cards/many.csv:
    post:
      summary: Create new Cards
      operationId: create-cards
      tags:
        - card
      parameters:
        - name: workspaceName
          in: path
          description: The name of the Workspace.
          required: true
          schema:
            type: string
          example: "workspaceTest"
      requestBody:
        description: Cards content payload.
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
            example: >-
              question,response
              questionTest,responseTest
      responses:
        '201':
          description: Cards successfully created.
        '404':
          description: Workspace not found.
        '409':
          description: One of the Cards already exists with the same id.
        '422':
          description: >-
            CSV fields null or empty, or missing headers.
