version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: learntool
    ports:
      - '5432:5432'

  backend:
    image: learntool/backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/learntool
      SPRING_DATASOURCE_USERNAME: $POSTGRES_USERNAME
      SPRING_DATASOURCE_PASSWORD: $POSTGRES_PASSWORD
      SPRING_DATASOURCE_PLATFORM: postgresql
      SPRING_DATASOURCE_INITIALIZATION-MODE: always
      SPRING_DATASOURCE_INITIALIZE: 1
      SPRING_DATASOURCE_SCHEMA: classpath:/db/postgresql-schema.sql
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DLL-AUTO: none
      SPRING_JPA_HIBERNATE_SHOW-SQL: 0
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
